name = "portfolio"
compatibility_date = "2024-09-26"

account_id = "$3f0b69666ae9df921de25c9b425afe7e"
workers_dev = true

# main = "src/worker.js"
site = { bucket = "./build", entry-point = "src/worker.js" }

[env.production]
name = "portfolio-production"
route = "https://api.kasu-it.dev/*"
account_id = "3f0b69666ae9df921de25c9b425afe7e"